### ISSUE TITLE
Cannot Update Beets Catalog

### ISSUE THREAD

**Issue by sneakysneakysneaky** [ampache/ampache#1466]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: nginx 1.6.2
 * Server operating system: Debian Jessie
 * Client operating system: macOS

 * Client type:
   - Web

# Settings

Default

# Description

I am trying to set up ampache for the first time. I would like to try to use my beets db as my source, but i am not able to add my database as a beets catalog. Nginx has access to the beets cli, db, and all of the music files. I see error messages about modules not being found & mysql syntax errors. For example, when i update the catalog, i see the following logs.

Cheers.

# Logs

```
2017-01-11 20:53:46 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:46 -0500 extension length 3600
2017-01-11 20:53:46 [admin] (ajax.server.php) -> Called for page: {index}
2017-01-11 20:53:48 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:48 -0500 extension length 3600
2017-01-11 20:53:48 [admin] (ajax.server.php) -> Called for page: {index}
2017-01-11 20:53:49 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:49 -0500 extension length 3600
2017-01-11 20:53:49 [admin] (ajax.server.php) -> Called for page: {index}
2017-01-11 20:53:50 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:50 -0500 extension length 3600
2017-01-11 20:53:50 [admin] (session) -> Session created: 8041f279d3bf479053bf745e70bbe639
2017-01-11 20:53:50 [admin] (browse) -> Show objects called for type {catalog}
2017-01-11 20:53:50 [admin] (autoload) -> 'Beets\Catalog' not found!
2017-01-11 20:53:50 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:50 -0500 extension length 3600
2017-01-11 20:53:50 [admin] (ajax.server.php) -> Called for page: {browse}
2017-01-11 20:53:50 [admin] (browse.ajax.php) -> Called for action: {get_filters}
2017-01-11 20:53:54 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:54 -0500 extension length 3600
2017-01-11 20:53:54 [admin] (session) -> Session created: 6895e319b6b1124e5d3c9cc301a0b9c8
2017-01-11 20:53:54 [admin] (autoload) -> 'Beets\Catalog' not found!
2017-01-11 20:53:54 [admin] (Core) -> Registered post form confirmation with SID 62f5ba2d9d60c9d046fd934fe27a3903 and expiration 1484189634 (3600 seconds from now)
2017-01-11 20:53:54 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:54 -0500 extension length 3600
2017-01-11 20:53:54 [admin] (autoload) -> 'Beets\Catalog' not found!
2017-01-11 20:53:54 [admin] (clean) -> Starting on Beets
2017-01-11 20:53:54 [admin] (autoload) -> 'Beets\Handler' not found!
2017-01-11 20:53:54 [admin] (autoload) -> 'Beets\CliHandler' not found!
2017-01-11 20:53:59 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:59 -0500 extension length 3600
2017-01-11 20:53:59 [admin] (session) -> Session created: f39482a54b299d16e6b27781f05e788f
2017-01-11 20:53:59 [admin] (browse) -> Show objects called for type {catalog}
2017-01-11 20:53:59 [admin] (autoload) -> 'Beets\Catalog' not found!
2017-01-11 20:53:59 [admin] (session) -> 27ctfcotfjh2ei5k36pajnl6f1 has been extended to Wed, 11 Jan 2017 21:53:59 -0500 extension length 3600
2017-01-11 20:53:59 [admin] (ajax.server.php) -> Called for page: {browse}
2017-01-11 20:53:59 [admin] (browse.ajax.php) -> Called for action: {get_filters}
2017-01-11 20:54:01 [admin] (Dba) -> Error: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1"]
2017-01-11 20:54:01 [admin] (Dba) -> Error: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1"]
2017-01-11 20:54:01 [admin] (Dba) -> Error: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1"]
2017-01-11 20:54:01 [admin] (Dba) -> Error: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1"]
2017-01-11 20:54:01 [admin] (clean) -> clean finished, 0 removed from Beets
2017-01-11 20:54:01 [admin] (catalog) -> Database cleanup started
2017-01-11 20:54:01 [admin] (catalog) -> Database cleanup ended
2017-01-11 20:54:01 [admin] (verify) -> Starting on Beets
```

**Comment by Phyks** [comment]
`2017-01-11 20:53:54 [admin] (autoload) -> 'Beets\Catalog' not found!` means you miss a module.

Could you update to `develop` branch and run `composer install` as described in the `README.md`? 3.8.2 is quite out of date.

Thanks

**Comment by sneakysneakysneaky** [comment]
I have updated to 3.8.3-develop via `git checkout develop; git pull; composer install`. I'm afraid i still see the error above.

**Comment by Phyks** [comment]
Definitely, autoloading does not work and it cannot load https://github.com/ampache/ampache/tree/develop/modules/Beets.

Tweaking with this directive https://github.com/ampache/ampache/blob/develop/composer.json#L356 might help, but it's been too long since I last had a look at Ampache code to be able to help you more with this :/

**Comment by sneakysneakysneaky** [comment]
Thanks for the kick in the right direction, @Phyks . I'm afraid i'm not a PHP dev & am trying to troubleshoot with one hand behind my back. :confused: 

I added the following to `composer.json` & ran `composer dump-autoload`.

```json
        "autoload": {
                "psr-4": {
                        "Lib\\": "lib/class",
                        "Beets\\": "modules/Beets"
                }
        }
```

Now when i update the catalog, the autolog errors are gone but the MySQL syntax errors are still present & no songs are added to the DB. I am runing MySQL 5.5.53, for the record.

**Comment by johanfleury** [comment]
I got the same library loading error here, on version 3.8.9. The `Beets/Catalog` class can't be found:

```
2018-09-15 21:12:22 [johan.fleury] (Core) -> Registered post form confirmation with SID 8f20922265d8fc67eec92b03d953cde7 and expiration 1537049542 (3600 seconds from now) 
2018-09-15 21:12:22 [johan.fleury] (session) -> 17eb9bc6kbhhgh42o9q832a247 has been extended to Sat, 15 Sep 2018 22:12:22 +0000 extension length 3600 
2018-09-15 21:12:22 [johan.fleury] (autoload) -> 'Beets\Catalog' not found! 
2018-09-15 21:12:22 [johan.fleury] (verify) -> Starting on Beets 
2018-09-15 21:12:22 [johan.fleury] (autoload) -> 'Beets\Handler' not found! 
2018-09-15 21:12:22 [johan.fleury] (autoload) -> 'Beets\CliHandler' not found! 
2018-09-15 21:12:23 [johan.fleury] (catalog) -> Database cleanup started 
2018-09-15 21:12:23 [johan.fleury] (catalog) -> Database cleanup ended 
```

**Comment by wagnered** [comment]
@johanfleury 

Thanks for bringing this to my attention.  For some reason @sneakysneakysneaky's fix described in his comment on Jan 12, 2017 did not get added to the repository.

I just added the fix and tested.  It has been pushed to the development branch. Don't know when it will be released.

You did not indicate whether your Ampache installation is the release or develop version. If it's the develop version just follow @sneakysneakysneaky's directions to add the fix..

**Comment by johanfleury** [comment]
Thank you for this fix.

I'm running the release version, I believe I'll just wait for the next release to test this feature then :)

**Comment by kuzi-moto** [comment]
I am running the latest development branch, and am unable to get any music to show up in my beets catalog. There are the same MySQL errors in the first post. Was there still some work to be done for getting this working?

**Comment by wagnered** [comment]
@kuzi-moto 

I am now taking a closer look at the issue.  I have installed Beets and am waiting for the database to "fill up".

**Comment by johanfleury** [comment]
I might be wrong actually, the error is more likley to be located at [modules/Beets/Catalog.php#L295](https://github.com/ampache/ampache-debian/blob/master/modules/Beets/Catalog.php#L295) or at [modules/Beets/Catalog.php#L308](https://github.com/ampache/ampache-debian/blob/master/modules/Beets/Catalog.php#L308) where an empty variable would result in a query like: `SELECT `id` FROM `song` WHERE `file` = ()`.

This query is indeed an invalid one:

```
MariaDB [ampache]> SELECT `id` FROM `song` WHERE `file` = ();
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
```

Also, I think there might actually be a flaw in trying to cast data as array when using equality comparison:

```
MariaDB [ampache]> SELECT `id` FROM `song` WHERE `file` = ('foo', 'bar');
ERROR 4078 (HY000): Illegal parameter data types varchar and row for operation '='
```

Hope this helps.

**Comment by wagnered** [comment]
@johanfleury  and @kuzi-moto 

I just created a Beets  catalog and it is currently importing data into the catalog with no errors.
Can each of you tell me what catalog action was executed to produce the errors?

DO I understand correctly that the MariaDB message is from the server log? 

I just clicked on the URL you gave and arrived at something called "ampache-debian" which hasn't been touched for at least 3 years.

You need to get the [latest release](https://github.com/ampache/ampache/releases/latest) and unpack it into the server's document root.

@kuzi-moto what version of Ampache do you have installed?

Sorry, but if I can't replicate the issue, I can't fix the issue. :frowning_face:

**Comment by johanfleury** [comment]
> I just created a Beets catalog and it is currently importing data into the catalog with no errors.
> Can each of you tell me what catalog action was executed to produce the errors?
> 

I think it was during the cleanup phase:

```
2018-12-04 03:18:01 [ampache] (clean) -> Starting on Beets 
2018-12-04 03:21:42 [ampache] (Dba) -> Error: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1"] 
2018-12-04 03:21:42 [ampache] (Dba) -> Error: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1"] 
2018-12-04 03:21:42 [ampache] (Dba) -> Error: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1"] 
2018-12-04 03:21:42 [ampache] (Dba) -> Error: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1"] 
2018-12-04 03:21:42 [ampache] (clean) -> clean finished, 0 removed from Beets 
```

> DO I understand correctly that the MariaDB message is from the server log?
> 

Yep, that's the output of MariaDB when I manually run Beets catalog queries with either an empty array or forged data. It's just there as an example.

> I just clicked on the URL you gave and arrived at something called "ampache-debian" which hasn't been touched for at least 3 years.
> 

I've probably fucked up between several tabs in my browser :)

The code is pretty much the same. I updated my comments accordingly.

> You need to get the [latest release](https://github.com/ampache/ampache/releases/latest) and unpack it into the server's document root.
> 

I'm on release 3.9.0.

**Comment by wagnered** [comment]
I'm beginning to think the problem is how beet is storing the information or problems with characters in the file's tag information or filename.

@johanfleury  could you let me know the name of the album, artist, title, etc that is causing the issue so I can try to emulate the problem? If it is a problem with characters in the tags, I'll have to see why they aren't being properly escaped for MySQL queries.

I when I update the beets catalog, I get the following mysql errors:
> 2018-12-04 21:01:22 [admin] (Dba) -> Error: ["01000",1265,"Data truncated for column 'album' at row 1"] 
2018-12-04 21:01:22 [admin] (Dba) -> Error: ["HY000",1366,"Incorrect integer value: 'Bee Gees' for column 'artist' at row 1"] 

Something is definitely wrong. It should definitely have an integer instead of string values.

Not once in 2200+ files did  I get the mysql error you described. 

I can look at the Beets catalog with an sqlite browser to check and compare the data with what is being written to mysql.

**Comment by wagnered** [comment]
@johanfleury For the Mysql error you posted, the function `protected function deleteSongs($songs)` should not be accessed at all if no songs have been deleted from the Beets database. 

As for the problem of the catalog not being able to be updated, It is probably because Beets.catalog.php is only inserting songs, not adding any album information.

There might still be other problems when updating, but 'first thing's first."

**Comment by wagnered** [comment]
@kuzi-moto and @johanfleury 

I think the issue has been resolved. I just pushed the changes to the develop branch.

I increased the precision of the last_added column to enable importing files added to the beets  db on the same day. Also, the major problem was that a datetime object was being improperly compared to a Unix timestamp.

Let me know if there are any more problems with importing from the beet db.

Not sure when these fixes will be  released.

**Comment by kuzi-moto** [comment]
> 
> 
> @kuzi-moto and @johanfleury
> 
> I think the issue has been resolved. I just pushed the changes to the develop branch.
> 
> I increased the precision of the last_added column to enable importing files added to the beets db on the same day. Also, the major problem was that a datetime object was being improperly compared to a Unix timestamp.
> 
> Let me know if there are any more problems with importing from the beet db.
> 
> Not sure when these fixes will be released.

I have updated my Ampache install, and unfortunately music still doesn't get added to the catalog. On looking at the error logs there doesn't seem to be any errors or any useful information.

**Comment by wagnered** [comment]
OK, I'll check.  Maybe the changes diodn't get pushed to the develop branch.

**Comment by wagnered** [comment]
Are you sure you are running Ampache 3.9.1-develop?

**Comment by kuzi-moto** [comment]
Yes footer says 3.9.1-develop, and the debug information says "f0dc28aa65ef59389b2b3c4587e84610d7ee2d62"

**Comment by wagnered** [comment]
OK, I will be cloning  remote branch to a separate folder to see what's going on.  My local repository creates the beets catalog successfully and I can also later add new files imported into the Beets DB.This is my working repo and the one I use to push the changes to the remote.

**Comment by kuzi-moto** [comment]
Very strange. Just to test I copied one of my albums into a test folder, then created a new beets catalog from that album and gave both ownership to my web user. Still does the same thing too.

**Comment by wagnered** [comment]
> Very strange. Just to test I copied one of my albums into a test folder, then created a new beets catalog from that album and gave both ownership to my web user. Still does the same thing too.

I don't understand. You don't indicate that you imported the test folder into a Beets db. using `beet import [-A|-a] /path/to/test folder`.

I just cloned/installed the develop version and it created a Beets catalog with no problem.

So I can't replicate your issue.

**Comment by kuzi-moto** [comment]
@wagnered I completely installed Ampache from scratch, then created a new beets database from a single album. I have no idea what I'm doing wrong but it still doesn't work and I can't find any logs that would point to the problem. Is there a way to create a catalog from the command line to see if that gives any information?

Something interesting I just tested out. Here is the output from running "catalog_update.inc" with the beets library:
`----------------------------------------------------------
Starting catalog operations...
        - Doing all catalog operations
----------------------------------------------------------

- Gathering art -
- Optimizing database tables -
------------------
`

and here is output from adding a single album to a regular local catalog:
`----------------------------------------------------------
Starting catalog operations...
        - Doing all catalog operations
----------------------------------------------------------

- Gathering art -
Reading catalog: test
- Start cleaning orphaned media entries -
           Clean Catalog
Cleaning the [ test ] Catalog...
Checking:
Reading:
1
/home/kuzi/ampache_music_test/Vava Voom/05 - What feat. Jansten.mp3
Catalog Clean Done. 0 files removed.------------------
- Start verifying media related to catalog entries -
           Verify Catalog
Updating the [ test ] catalog
Verified:
Reading:
22
Catalog Verify Done. 19 of 22 files updated.-------------------
- Start adding new media -
           Starting New Media Search
Starting New Media Search on [ test ] catalog
Found: None
Reading:
17
           Art Search
Starting Art Search. . .
Searched: None
Reading:MC Plus+ and The Empty Set
Chip Hop
2
Catalog Update Finished.  Total Time: [00:01] Total Media: [17] Media Per Second: [17.00]
----------------
- Optimizing database tables -
------------------
`

It appears to only be doing "gathering art"? Any more testing I can do here?

**Comment by mitchray** [comment]
Closing due to inactivity, reopen if this is still relevant in latest version
