### ISSUE TITLE
Empty channel stream

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#1616]
Hi

I setup a channel using a play list(tried with multiple playlists) and I enabled channel in the config. I believe I set the 
transcodes

I run the channel and type ffplay (or mpv) streamurl.ogg (or mp3) and I get a stream but it is empty. If there is no stream (like stopped channel) both ffplay and mpv drops the connection naturally

This is what I see in the log over and over again
2017-10-11 17:01:57 [ampache] (stream) -> Stream process about to be killed. pid:19733 

which stop when I kill the channel.

I am using ampache 3.83 (from github release) on Debian Wheezy php 5.6 Apache 2.2.22

I cant install the latest dev because composer complaints that couple modules requires php7 which is not available on Wheezy and I do not want to f..k with my php server stuff atm. 

Is there a way to disable those modules? I have no idea what composer is and how it is used, I am just a user.

```
  Problem 1
    - Installation request for tightenco/collect v5.5.9 -> satisfiable by tightenco/collect[v5.5.9].
    - tightenco/collect v5.5.9 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
  Problem 2
    - tightenco/collect v5.5.9 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - kunalvarma05/dropbox-php-sdk v0.2.1 requires tightenco/collect ^5.2 -> satisfiable by tightenco/collect[v5.5.9].
    - Installation request for kunalvarma05/dropbox-php-sdk v0.2.1 -> satisfiable by kunalvarma05/dropbox-php-sdk[v0.2.1]
```

Here is the transcode portion
```

; (e.g. if you store everything in FLAC, but don't want to ever stream that.)
; transcode_TYPE         = {allowed|required|false}
; DEFAULT: false
;;; Audio
transcode_m4a = "1"
transcode_flac     = required
;transcode_mpc      = required
;transcode_ogg      = required
;transcode_oga      = required
transcode_wav      = required
transcode_wma      = required
;transcode_aif      = required
;transcode_aiff     = required
transcode_ape     = required
;transcode_shn     = required
transcode_mp3      = allowed
;;; Video
transcode_avi      = false
transcode_mkv      = false
transcode_mpg      = false
transcode_mpeg     = false
transcode_m4v      = false
transcode_mp4      = false
transcode_mov      = false
transcode_wmv      = false
transcode_ogv      = false
transcode_divx     = false
transcode_m2ts     = false
transcode_webm     = false

; Default audio output format
; DEFAULT: none
encode_target = mp3

; Default video output format
; DEFAULT: none 
;encode_video_target = webm

; Override the default output format on a per-type basis
; encode_target_TYPE = TYPE
; DEFAULT: none
; encode_target_flac = ogg
encode_target_flac = mp3
 
; Override the default TYPE transcoding behavior on a per-player basis
; transcode_player_PLAYER_TYPE = TYPE
; Valid PLAYER is: webplayer, api
; DEFAULT: none
;transcode_player_webplayer_m4a = required
transcode_player_webplayer_flac = required
;transcode_player_webplayer_mpc = required

; Override the default output format on a per-player basis
; encode_player_PLAYER_target = TYPE
; Valid PLAYER is: webplayer, api
; DEFAULT: none
;encode_player_webplayer_target = mp3
;encode_player_api_target = mp3

; Allow clients to override transcode settings (output type, bitrate, codec ...)
; DEFAULT: true

```

**Comment by wagnered** [comment]
@gerroon,

Please use the template at [https://github.com/ampache/ampache/wiki/Issues](https://github.com/ampache/ampache/wiki/Issues) to give us more information.

The problems you had have been with the develop version has been fixed.  Please try again with latest develop version.

**Comment by gerroon** [comment]
@wagnered 

Like I said I cant try the latest version because of composer needing php7 for some modules. If you can tell me how to get the latest version on my system which is Debian Wheezy php5 I would be more than happy to test out.

I use v3.8.3 from the release tab.

**Comment by wagnered** [comment]
@gerroon,

To repeat, I just fixed your problem with  3.8.4-develop. It now accepts PHP-5.6.30. Others had already reported the problem:

If you don't want to try it, we still need more information to give more assistance.

**Comment by gerroon** [comment]
@wagnered 

I am sorry I misunderstood your reply, I thought you fixed something else.

"The problems you had have been with the develop version has been fixed."


This was not clear to me, it sounded like you were referring to stream issues only.

Anyway I will try it.

thanks

**Comment by gerroon** [comment]
Hi

I still cant get the channel to work. I also see some new issues popping up here. I am not sure if they are related to channels or not . 

"The channel issue still throws stream process about to be kiled"

I am using Debian 7.1 x32 , ffmpeg 1.0.10, Apache 2.2.22, Php 5.6.31, Mysql 14.14


```

2017-10-13 21:43:15 [XXXXXXXk] (play) ->   configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --c›│··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libavformat    54. 29.104 / 54. 29.104                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libavdevice    54.  2.101 / 54.  2.101                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libavfilter     3. 17.100 /  3. 17.100                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libswscale      2.  1.101 /  2.  1.101                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libswresample   0. 15.100 /  0. 15.100                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libpostproc    52.  0.100 / 52.  0.100                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) -> %FILE: No such file or directory                                                                                                                                        │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->                                                                                                                                                                         │··························
  2017-10-13 21:43:15 [XXXXXXXk] (stream) -> Stream process about to be killed. pid:7630                                                                                                                           │··························
  2017-10-13 21:43:15 [XXXXXXXk] (stream) -> Stream process about to be killed. pid:7632                                                                                                                           │··························
  2017-10-13 21:43:22 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): invalid character in attribute value in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190) │··························
  2017-10-13 21:43:22 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): attributes construct error in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190)           │··························
  2017-10-13 21:43:22 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): Couldn't find end of Start Tag artist line 2 in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.›│··························
  2017-10-13 21:43:22 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): PCDATA invalid Char value 25 in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190)         │··························
  2017-10-13 21:43:49 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): invalid character in attribute value in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190) │··························
  2017-10-13 21:43:49 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): attributes construct error in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190)           │··························
  2017-10-13 21:43:49 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): Couldn't find end of Start Tag artist line 2 in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.›│··························
  2017-10-13 21:43:49 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): PCDATA invalid Char value 25 in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190)         │··························
                                                                                                                                                                                                                   │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --c›│··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libavformat    54. 29.104 / 54. 29.104                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libavdevice    54.  2.101 / 54.  2.101                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libavfilter     3. 17.100 /  3. 17.100                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libswscale      2.  1.101 /  2.  1.101                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libswresample   0. 15.100 /  0. 15.100                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->   libpostproc    52.  0.100 / 52.  0.100                                                                                                                                │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) -> %FILE: No such file or directory                                                                                                                                        │··························
  2017-10-13 21:43:15 [XXXXXXXk] (play) ->                                                                                                                                                                         │··························
  2017-10-13 21:43:15 [XXXXXXXk] (stream) -> Stream process about to be killed. pid:7630                                                                                                                           │··························
  2017-10-13 21:43:15 [XXXXXXXk] (stream) -> Stream process about to be killed. pid:7632                                                                                                                           │··························
  2017-10-13 21:43:22 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): invalid character in attribute value in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190) │··························
  2017-10-13 21:43:22 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): attributes construct error in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190)           │··························
  2017-10-13 21:43:22 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): Couldn't find end of Start Tag artist line 2 in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.›│··························
  2017-10-13 21:43:22 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): PCDATA invalid Char value 25 in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190)         │··························
  2017-10-13 21:43:49 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): invalid character in attribute value in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190) │··························
  2017-10-13 21:43:49 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): attributes construct error in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190)           │··························
  2017-10-13 21:43:49 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): Couldn't find end of Start Tag artist line 2 in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.›│··························
  2017-10-13 21:43:49 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): PCDATA invalid Char value 25 in Entity, line: 2 in file /var/www/ampache-dev-github/lib/class/subsonic_api.class.php(190)         │··························
                                                                                                                                                                                                                   │··························
                                                                                             
```

**Comment by wagnered** [comment]
@gerroon,

I need to see your entire ampache.cfg.php file.

**Comment by gerroon** [comment]
@wagnered I already posted that? 

config
https://paste.debian.net/hidden/111389f3/

**Comment by gerroon** [comment]
@wagnered 

Not sure if the prev one was missing anything, 

try this one then

https://paste.debian.net/hidden/1de48481/

**Comment by wagnered** [comment]
Sorry, I didn't see a reference to the full config file in this message chain. but both of your config posts showed enough to reveal one problem:

`transcode_input = "-i %FILE"` should be `transcode_input = "-i **%FILE%**

There may be other problems, but this confirms the error shown in the above debug log.

**Comment by gerroon** [comment]
ahhhaa , ok let me try it.

**Comment by wagnered** [comment]
I don't know if you got my edited message but I made a typo.

The switch should be: `transcode_input = "-i %FILE%"`
Notice the **two** percent signs (%)

**Comment by gerroon** [comment]
That was it thank you so much.  I have no idea how that line became to be that way :(

**Comment by mitchray** [comment]
Seems to be resolved, closing
