### ISSUE TITLE
Show missing album doesn't work properly when letters used in track numbers

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1984]
# Issue Template

## Environment

* Ampache version: 4.0.0-develop
* Client type: Any

## Description

Ampache is looking for an integer when displaying tracks, so if the release is a vinyl that uses letters to indicate the side, such as (A1, A2, B1, B2, etc.) on each track it doesn't show the Title, Track, or Disk. It also doesn't show the Artist, but that's an issue for all wanted albums. 

![image](https://user-images.githubusercontent.com/17068090/61728209-63779300-ad3a-11e9-8c22-12cae4d364dc.png)

## Logs

Ampache log:

```Log
2019-07-23 10:51:58 [ampache] (session.class) -> Existing session found
2019-07-23 10:51:58 [kuzi] (session.class) -> gmg0vf6tu40tj56nvpkkpnvnuu has been extended to Wed, 24 Jul 2019 10:51:58 -0500 extension length 86400
2019-07-23 10:51:58 [kuzi] (session.class) -> Session created: 161e3366318dd9c1bbef7ab8e8c9effa
2019-07-23 10:51:59 [ampache] (session.class) -> Existing session found
2019-07-23 10:51:59 [kuzi] (session.class) -> gmg0vf6tu40tj56nvpkkpnvnuu has been extended to Wed, 24 Jul 2019 10:51:59 -0500 extension length 86400
2019-07-23 10:51:59 [ampache] (session.class) -> Existing session found
2019-07-23 10:51:59 [kuzi] (session.class) -> gmg0vf6tu40tj56nvpkkpnvnuu has been extended to Wed, 24 Jul 2019 10:51:59 -0500 extension length 86400
2019-07-23 10:51:59 [kuzi] (ajax.server) -> Called for page: {index}
2019-07-23 10:51:59 [kuzi] (rating.lib) -> Get artist rating 653
2019-07-23 10:51:59 [kuzi] (rating.lib) -> Get artist rating 243
2019-07-23 10:51:59 [kuzi] (rating.lib) -> Get artist rating 365
2019-07-23 10:51:59 [kuzi] (rating.lib) -> Get artist rating 382
2019-07-23 10:51:59 [kuzi] (rating.lib) -> Get artist rating 1110
2019-07-23 10:51:59 [kuzi] (rating.lib) -> Get artist rating 1261
2019-07-23 10:51:59 [ampache] (session.class) -> Existing session found
2019-07-23 10:51:59 [kuzi] (session.class) -> gmg0vf6tu40tj56nvpkkpnvnuu has been extended to Wed, 24 Jul 2019 10:51:59 -0500 extension length 86400
2019-07-23 10:51:59 [kuzi] (ajax.server) -> Called for page: {index}
2019-07-23 10:51:59 [ampache] (session.class) -> Existing session found
2019-07-23 10:51:59 [kuzi] (session.class) -> gmg0vf6tu40tj56nvpkkpnvnuu has been extended to Wed, 24 Jul 2019 10:51:59 -0500 extension length 86400
2019-07-23 10:51:59 [kuzi] (session.class) -> Session created: 0e89ec809888af971e42a6b7b92664b8
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'A1' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'A1' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'A1' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'A1' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (song_preview.class) -> Unable to insert
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'A2' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'A2' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'A2' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'A2' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (song_preview.class) -> Unable to insert
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'B1' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'B1' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'B1' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'B1' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (song_preview.class) -> Unable to insert
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'B2' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'B2' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'B2' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (dba.class) -> Error: ["22007",1366,"Incorrect integer value: 'B2' for column `ampache`.`song_preview`.`track` at row 1"]
2019-07-23 10:52:02 [kuzi] (song_preview.class) -> Unable to insert
2019-07-23 10:52:07 [kuzi] (art.class) -> Searching using:["db","tags","folder"]
2019-07-23 10:52:07 [kuzi] (art.class) -> Method used: gather_db
2019-07-23 10:52:07 [kuzi] (art.class) -> results:{"db":true}
2019-07-23 10:52:07 [kuzi] (browse.class) -> Show objects called for type {song_preview}
```

**Comment by lachlan-00** [comment]
At least i have plenty of daft punk to test!

This should be converted into disk/track or at the very least stripped out.

**Comment by kuzi-moto** [comment]
Also, I wonder if the Artist column should be fixed? I mean, it could probably be removed, though there are some albums that have different artists for certain tracks, and VA albums.

**Comment by lachlan-00** [comment]
can you test this regex? i have that album but not tagged that way.
![image](https://user-images.githubusercontent.com/1305249/62619661-a3ee2800-b95a-11e9-9d70-4ff8bfb24e6e.png)

```
preg_replace('/[\D]/g', '', $results['disk']), 
```

**Comment by lachlan-00** [comment]
Sanitize disk is part of develop now so I think this is resolved?

To do this it's a straight a-z 1-26 swap

**Comment by kuzi-moto** [comment]
Interestingly now I can't get the same Daft Punk albums to show. Says it doesn't find anything. I tried another artist, and was able to find some more cases where it was happening:

* https://musicbrainz.org/release-group/e3b81d2d-e3b6-412c-a83d-e431432d525a

![image](https://user-images.githubusercontent.com/17068090/67225259-83c9f300-f3f8-11e9-9535-5f1b52ef756c.png)

also these:

* https://musicbrainz.org/release-group/044075e8-01a2-3791-91a9-ba31201077d7
* https://musicbrainz.org/release-group/66a2be28-5947-4a02-a085-613bc9132579
* https://musicbrainz.org/release-group/4c6394f2-e3e0-3a54-8c98-21c1ec08ab63
* https://musicbrainz.org/release-group/c2f621f4-b34a-4174-b56e-e49afa06f34b

But interestingly, not this one:

* https://musicbrainz.org/release-group/3f60c0f9-cfe5-4ec2-acd2-471ecd55400e

**Comment by kuzi-moto** [comment]
Also, the **Artist** field is never populated. We should probably have it filled in, as some albums have tracks with other artists than the Album Artist.

**Comment by lachlan-00** [comment]
Okay so that must mean that the process of loading these is skipping them.

I might just leave a single track in for daft Punk and see if I can fill the gaps

**Comment by lachlan-00** [comment]
testing this now and i'm not seeing singles pop in.

**Comment by lachlan-00** [comment]
interestingly the text for artists is there when you look in the source. seems all over a bit weird

**Comment by lachlan-00** [comment]
fixed in edge ;)

**Comment by kuzi-moto** [comment]
Hmm, I am seeing artist field filled out in other missing albums, but the example I posted last time is still broken, and nothing has changed. Could it be because it's a single and not an ep/album?

**Comment by lachlan-00** [comment]
Singles still aren't even making the list for me. I don't know if anything has changed with musicbrainz but something is different.

**Comment by kuzi-moto** [comment]
Do you have them enabled in the config? I don't believe it was enabled by default for me.

**Comment by lachlan-00** [comment]
I put every release type in the wanted class but the musicbrainz query doesn't seem to return them so I think singles are ignored there.

**Comment by lachlan-00** [comment]
the musicbrainz library we use seems to not find everything https://github.com/mikealmond/MusicBrainz

it's probably a change on the MB end? they are all release groups so i'm not sure why they're not coming in yet.

```
stdClass Object 
 ( 
     [type-id] => e431f5f6-b5d2-343d-8b36-72607fffb74b 
     [isnis] => Array 
         ( 
             [0] => 0000000123531208 
         ) 
  
     [begin_area] => stdClass Object 
         ( 
             [name] => Paris 
             [sort-name] => Paris 
             [disambiguation] =>  
             [iso-3166-2-codes] => Array 
                 ( 
                     [0] => FR-75 
                 ) 
  
             [id] => dc10c22b-e510-4006-8b7f-fecb4f36436e 
         ) 
  
     [name] => Daft Punk 
     [end_area] =>  
     [id] => 056e4f3e-d505-4dad-8ec1-d04f521cbb56 
     [ipis] => Array 
         ( 
         ) 
  
     [gender] =>  
     [gender-id] =>  
     [disambiguation] => French electronic music duo 
     [life-span] => stdClass Object 
         ( 
             [end] =>  
             [begin] => 1993 
             [ended] =>  
         ) 
  
     [release-groups] => Array 
         ( 
             [0] => stdClass Object 
                 ( 
                     [secondary-type-ids] => Array 
                         ( 
                         ) 
  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [primary-type] => Album 
                     [title] => Homework 
                     [secondary-types] => Array 
                         ( 
                         ) 
  
                     [id] => 00054665-89fa-33d5-a8f0-1728ea8c32c3 
                     [first-release-date] => 1997-01-20 
                 ) 
  
             [1] => stdClass Object 
                 ( 
                     [id] => 48117b90-a16e-34ca-a514-19c702df1158 
                     [first-release-date] => 2001-02-26 
                     [secondary-type-ids] => Array 
                         ( 
                         ) 
  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [primary-type] => Album 
                     [title] => Discovery 
                     [secondary-types] => Array 
                         ( 
                         ) 
  
                 ) 
  
             [2] => stdClass Object 
                 ( 
                     [id] => f9e8042a-674e-3f01-80ec-7f0ab1c537df 
                     [first-release-date] => 2005-03-09 
                     [primary-type] => Album 
                     [secondary-types] => Array 
                         ( 
                         ) 
  
                     [title] => Human After All 
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [secondary-type-ids] => Array 
                         ( 
                         ) 
  
                 ) 
  
             [3] => stdClass Object 
                 ( 
                     [primary-type] => Album 
                     [secondary-types] => Array 
                         ( 
                         ) 
  
                     [title] => Random Access Memories 
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [secondary-type-ids] => Array 
                         ( 
                         ) 
  
                     [id] => aa997ea0-2936-40bd-884d-3af8a0e064dc 
                     [first-release-date] => 2013-05-17 
                 ) 
  
             [4] => stdClass Object 
                 ( 
                     [id] => b791a9cc-dc92-45ee-b5b9-be5617823411 
                     [first-release-date] => 1999 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => dd2a21e1-0c00-3729-a7a0-de60b84eb5d1 
                         ) 
  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [primary-type] => Album 
                     [title] => D.A.F.T. : A Story About Dogs, Androids, Firemen And Tomatoes 
                     [secondary-types] => Array 
                         ( 
                             [0] => Compilation 
                         ) 
  
                 ) 
  
             [5] => stdClass Object 
                 ( 
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [primary-type] => Album 
                     [secondary-types] => Array 
                         ( 
                             [0] => Compilation 
                         ) 
  
                     [title] => Musique, Volume 1: 1993–2005 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => dd2a21e1-0c00-3729-a7a0-de60b84eb5d1 
                         ) 
  
                     [first-release-date] => 2006-03-29 
                     [id] => 66ecf2c3-441f-3981-b85f-a005d9cc582d 
                 ) 
  
             [6] => stdClass Object 
                 ( 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => dd2a21e1-0c00-3729-a7a0-de60b84eb5d1 
                         ) 
  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [primary-type] => Album 
                     [secondary-types] => Array 
                         ( 
                             [0] => Compilation 
                         ) 
  
                     [title] => Greatest Hits 
                     [first-release-date] => 2006 
                     [id] => 3ab059bc-281d-4719-90c6-ed130fa2bd20 
                 ) 
  
             [7] => stdClass Object 
                 ( 
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [title] => Digital Decks 
                     [secondary-types] => Array 
                         ( 
                             [0] => Compilation 
                         ) 
  
                     [primary-type] => Album 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => dd2a21e1-0c00-3729-a7a0-de60b84eb5d1 
                         ) 
  
                     [first-release-date] => 2009-03-14 
                     [id] => 68360aa5-6003-403d-8b4f-d04cbda9516c 
                 ) 
  
             [8] => stdClass Object 
                 ( 
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [title] => Decks n' Drums n' 909 
                     [secondary-types] => Array 
                         ( 
                             [0] => Compilation 
                             [1] => DJ-mix 
                         ) 
  
                     [primary-type] => Album 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => dd2a21e1-0c00-3729-a7a0-de60b84eb5d1 
                             [1] => 0d47f47a-3fe5-3d69-ac9d-d566c23968bf 
                         ) 
  
                     [id] => 94c9ccc0-0c9b-306b-8d91-3a45bbdf30bc 
                     [first-release-date] => 2002 
                 ) 
  
             [9] => stdClass Object 
                 ( 
                     [first-release-date] => 2001-10-01 
                     [id] => 8093fc8c-942c-30f3-a224-49dbc718f8e4 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [title] => Alive 1997 
                     [primary-type] => Album 
                 ) 
  
             [10] => stdClass Object 
                 ( 
                     [id] => fac1af8d-0676-3884-9d70-2c314c158d5d 
                     [first-release-date] => 2001 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [title] => Live @ Rex Club Paris 
                     [primary-type] => Album 
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                 ) 
  
             [11] => stdClass Object 
                 ( 
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [title] => Daft Punk Live in NYC 
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [primary-type] => Album 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [id] => 63c8cb6e-91bb-4fb9-a5bc-f97a6980957b 
                     [first-release-date] => 2005 
                 ) 
  
             [12] => stdClass Object 
                 ( 
                     [id] => 4bac3d70-deea-3d80-85c4-8be9f90558e6 
                     [first-release-date] => 2007-11-14 
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [title] => Alive 2007 
                     [primary-type] => Album 
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                 ) 
  
             [13] => stdClass Object 
                 ( 
                     [first-release-date] => 2007-12-13 
                     [id] => 11bbba73-bb2f-4723-a14b-a706bad16467 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [title] => 2007-12-13: Sidney Myer Music Bowl, Melbourne, Australia 
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [primary-type] => Album 
                 ) 
  
             [14] => stdClass Object 
                 ( 
                     [id] => 6f374838-0f94-3066-a8f5-3ec758e4dace 
                     [first-release-date] => 2007 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [primary-type] => Album 
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [title] => 2006-06-30: Eurockéennes, Belfort, France 
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                 ) 
  
             [15] => stdClass Object 
                 ( 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [title] => Alive 2007 / Alive 1997 
                     [primary-type] => Album 
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [id] => ec8e9600-b802-48ff-a387-ace28cb90642 
                     [first-release-date] => 2009 
                 ) 
  
             [16] => stdClass Object 
                 ( 
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [primary-type] => Album 
                     [title] => 2006-04-29: Coachella Valley Music Festival 
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [id] => d395a8cf-71dd-330d-99bd-fca3ec0c59c5 
                     [first-release-date] =>  
                 ) 
  
             [17] => stdClass Object 
                 ( 
                     [id] => cb83a67b-428e-379c-bfd0-58031e4ee700 
                     [first-release-date] =>  
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [title] => 2007-10-27: Vegoose 2007: Sam Boyd Stadium, Las Vegas, NV, USA 
                     [primary-type] => Album 
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                 ) 
  
             [18] => stdClass Object 
                 ( 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 6fd474e2-6b58-3102-9d17-d6f7eb7da0a0 
                         ) 
  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [primary-type] => Album 
                     [title] => Alive Summer 2006 
                     [secondary-types] => Array 
                         ( 
                             [0] => Live 
                         ) 
  
                     [id] => ba991e16-9f65-43ac-931b-3a4cbc903cab 
                     [first-release-date] =>  
                 ) 
  
             [19] => stdClass Object 
                 ( 
                     [first-release-date] => 2001 
                     [id] => 2a7840ab-9567-37f4-85b8-3208db09434b 
                     [primary-type] => Album 
                     [title] => Discovery: Bonus Tracks From daftclub.com 
                     [secondary-types] => Array 
                         ( 
                             [0] => Remix 
                         ) 
  
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 0c60f497-ff81-3818-befd-abfc84a4858b 
                         ) 
  
                 ) 
  
             [20] => stdClass Object 
                 ( 
                     [primary-type] => Album 
                     [secondary-types] => Array 
                         ( 
                             [0] => Remix 
                         ) 
  
                     [title] => Daft Club 
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 0c60f497-ff81-3818-befd-abfc84a4858b 
                         ) 
  
                     [id] => 1fd2e0fe-90f6-35ca-92c0-d816ab3bb79c 
                     [first-release-date] => 2003-11-27 
                 ) 
  
             [21] => stdClass Object 
                 ( 
                     [id] => 16ea0f65-3462-3283-a3eb-e81dcc92c1d5 
                     [first-release-date] => 2006-03-29 
                     [title] => Human After All: Remixes 
                     [secondary-types] => Array 
                         ( 
                             [0] => Remix 
                         ) 
  
                     [primary-type] => Album 
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 0c60f497-ff81-3818-befd-abfc84a4858b 
                         ) 
  
                 ) 
  
             [22] => stdClass Object 
                 ( 
                     [id] => 15af54b9-b687-4450-bab8-a0cac036ab3b 
                     [first-release-date] => 2009-05-20 
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [disambiguation] =>  
                     [secondary-types] => Array 
                         ( 
                             [0] => Remix 
                         ) 
  
                     [title] => Remix After All 
                     [primary-type] => Album 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 0c60f497-ff81-3818-befd-abfc84a4858b 
                         ) 
  
                 ) 
  
             [23] => stdClass Object 
                 ( 
                     [primary-type] => Album 
                     [title] => TRON: Legacy R3C0NF1GUR3D 
                     [secondary-types] => Array 
                         ( 
                             [0] => Soundtrack 
                             [1] => Remix 
                         ) 
  
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 22a628ad-c082-3c4f-b1b6-d41665107b88 
                             [1] => 0c60f497-ff81-3818-befd-abfc84a4858b 
                         ) 
  
                     [id] => bc49de56-46c7-4250-b987-a0cd43e73279 
                     [first-release-date] => 2011-04-04 
                 ) 
  
             [24] => stdClass Object 
                 ( 
                     [id] => b585e56e-69cb-4f53-9597-320af5e5f541 
                     [first-release-date] => 2010-12-06 
                     [secondary-type-ids] => Array 
                         ( 
                             [0] => 22a628ad-c082-3c4f-b1b6-d41665107b88 
                         ) 
  
                     [disambiguation] =>  
                     [primary-type-id] => f529b476-6e62-324f-b0aa-1f3e33d313fc 
                     [primary-type] => Album 
                     [secondary-types] => Array 
                         ( 
                             [0] => Soundtrack 
                         ) 
  
                     [title] => TRON: Legacy 
                 ) 
  
         ) 
  
     [type] => Group 
     [area] => stdClass Object 
         ( 
             [name] => France 
             [sort-name] => France 
             [disambiguation] =>  
             [iso-3166-1-codes] => Array 
                 ( 
                     [0] => FR 
                 ) 
  
             [id] => 08310658-51eb-3801-80de-5a0739207115 
         ) 
  
     [sort-name] => Daft Punk 
     [country] => FR 
 ) 
```

**Comment by lachlan-00** [comment]
apparently it is restricted using the lookup method.
https://www.howtobuildsoftware.com/index.php/how-do/b7eY/api-musicbrainz-musicbrainz-api-get-all-release-groups-and-release-dates

**Comment by lachlan-00** [comment]
lets make that a separate issue. mb library needs to use lookup for the extra release types.

i know what to do just have to do some play with the queries
