### ISSUE TITLE
Cron keeps crashing with Error Call to undefined method stdClass::getId()

### ISSUE THREAD

**Issue by mediadev123** [ampache/ampache#3393]
## Description
I noticed that my corn job (systemd service technically), keeps crashing with:
```
Nov 22 06:45:41 music-server php[195690]: Error Call to undefined method stdClass::getId()
Nov 22 06:45:41 music-server php[195690]: (thrown in /var/www/ampache/src/Module/Art/Collector/SpotifyCollectorModule.php:173)
Nov 22 06:45:41 music-server php[195690]: Stack Trace:
Nov 22 06:45:41 music-server php[195690]:   0) Ampache\Module\Art\Collector\SpotifyCollectorModule->collect()
Nov 22 06:45:41 music-server php[195690]:      at /var/www/ampache/src/Module/Art/Collector/ArtCollector.php:146
Nov 22 06:45:41 music-server php[195690]:   1) Ampache\Module\Art\Collector\ArtCollector->collect()
Nov 22 06:45:41 music-server php[195690]:      at /var/www/ampache/src/Repository/Model/Catalog.php:1896
Nov 22 06:45:41 music-server php[195690]:   2) Ampache\Repository\Model\Catalog::gather_art_item()
Nov 22 06:45:41 music-server php[195690]:      at /var/www/ampache/src/Repository/Model/Catalog.php:2002
Nov 22 06:45:41 music-server php[195690]:   3) Ampache\Repository\Model\Catalog->gather_art()
Nov 22 06:45:41 music-server php[195690]:      at /var/www/ampache/src/Module/Catalog/Update/UpdateCatalog.php:192
Nov 22 06:45:41 music-server php[195690]:   4) Ampache\Module\Catalog\Update\UpdateCatalog->update()
Nov 22 06:45:41 music-server php[195690]:      at /var/www/ampache/src/Module/Cli/UpdateCatalogCommand.php:70
Nov 22 06:45:41 music-server php[195690]:   5) Ampache\Module\Cli\UpdateCatalogCommand->execute()
Nov 22 06:45:41 music-server php[195690]:      at /var/www/ampache/vendor/adhocore/cli/src/Application.php:366
Nov 22 06:45:41 music-server php[195690]:   6) Ahc\Cli\Application->doAction()
Nov 22 06:45:41 music-server php[195690]:      at /var/www/ampache/vendor/adhocore/cli/src/Application.php:280
Nov 22 06:45:41 music-server php[195690]:   7) Ahc\Cli\Application->handle()
Nov 22 06:45:41 music-server php[195690]:      at /var/www/ampache/bin/cli:79
```

Specifically, this bug seems to have been introduced in 1e0f399fd2b3e4729ecc105302fa3e1b23bba3a8. I am tagging you, @lachlan-00 because you made this commit recently and maybe can offer some context.

I am not too familiar with PHP but it seems to me that whatever parsed the server response didn't create a correct stdclass with getters. A quick `print_r($response)` at  `/var/www/ampache/src/Module/Art/Collector/SpotifyCollectorModule.php:173` reveals that the id is indeed present from the server response:

```
(
    [artists] => stdClass Object
        (
            [href] => [redcated]
            [items] => Array
                (
                    [0] => stdClass Object
                        (
                            [external_urls] => stdClass Object
                                (
                                    [spotify] => [redcated]
                                )

                            [followers] => stdClass Object
                                (
                                    [href] =>
                                    [total] => [redcated]
                                )

                            [genres] => Array
                                (
                                )

                            [href] => [redcated]
                            [id] => [redcated] 
                            [images] => Array
                                (
                                )

                            [name] => [redcated]
                            [popularity] => [redcated]
                            [type] => artist
                            [uri] =>[redcated]
                        )
```

### To reproduce

I am not 100% sure but I am using the standard systemd service from the install guide in the wiki:

```
$systemctl cat ampache_catalog.service
# /etc/systemd/system/ampache_catalog.service
[Unit]
Description=Removes old songs from catalog, then adds new ones and finally gather art to the catalog
After=network.target remote-fs.target nss-lookup.target mariadb.service
Documentation=https://github.com/ampache/ampache/wiki

[Service]
PrivateTmp=true
KillMode=mixed
Type=oneshot
User=ampache
Group=ampache
ExecStart=php bin/cli run:updateCatalog -cagv
WorkingDirectory=/var/www/ampache
ProtectSystem=yes

[Install]
WantedBy=multi-user.target
```

My art order is in the config is: art_order = "db,folder,spotify,tags" and I have configured a valid spotify_client_id & secret. wanted_types is "album,official,single,ep,live,compilation" , not sure if that's relevant though... 

## Environment

* Ampache version: 825a480bfd561fd41ea6e1a91b5cd67a55fe6223
* Web server + version: Apache/2.4.54 (Debian)
* Server operating system: Debian bullseye (11)

I have also confirmed that composer is up to date (it wasn't but the error keeps occurring):
```
$composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package nabil1337/case-helper is abandoned, you should avoid using it. Use marcusball/case-helper instead.
Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> @php resources/scripts/composer/check_tag_tools.php
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
77 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

git status also says that the repo is clean (no modifications not tracked by gitignore)

**Comment by lachlan-00** [comment]
it's a copy paste that i missed replacing common parts in some other areas.

i only saw it after i fixed up the release again so that means a new point for this

**Comment by lachlan-00** [comment]
releasing 5.5.5 to fix this mistake, not a great one to have in a new release

**Comment by mediadev123** [comment]
> releasing 5.5.5 to fix this mistake, not a great one to have in a new release

I am not sure that's fixed. I am on tag 5.5.5 (f05299300be1064fa1f8c4bb7fe6944f3ee6ac90), and this error still shows up when I run `php bin/cli run:updateCatalog -cagv`:

```Reading Catalog: "music"
Start cleaning orphaned media entries
1
[redacted]
0 files removed.
------------------
Start adding new media
Starting New Media Search
Starting New Media Search on "[ music ]" Catalog
Found: None
Reading:
0
Total Time: [00:00] Total Media: [0] Media Per Second: [N/A]
------------------
Start searching new media art
Error Call to undefined method stdClass::getId()
(thrown in /var/www/ampache/src/Module/Art/Collector/SpotifyCollectorModule.php:173)

Stack Trace:

  0) Ampache\Module\Art\Collector\SpotifyCollectorModule->collect()
     at /var/www/ampache/src/Module/Art/Collector/ArtCollector.php:146
  1) Ampache\Module\Art\Collector\ArtCollector->collect()
     at /var/www/ampache/src/Repository/Model/Catalog.php:1896
  2) Ampache\Repository\Model\Catalog::gather_art_item()
     at /var/www/ampache/src/Repository/Model/Catalog.php:2002
  3) Ampache\Repository\Model\Catalog->gather_art()
     at /var/www/ampache/src/Module/Catalog/Update/UpdateCatalog.php:192
  4) Ampache\Module\Catalog\Update\UpdateCatalog->update()
     at /var/www/ampache/src/Module/Cli/UpdateCatalogCommand.php:70
  5) Ampache\Module\Cli\UpdateCatalogCommand->execute()
     at /var/www/ampache/vendor/adhocore/cli/src/Application.php:366
  6) Ahc\Cli\Application->doAction()
     at /var/www/ampache/vendor/adhocore/cli/src/Application.php:280
  7) Ahc\Cli\Application->handle()
     at /var/www/ampache/bin/cli:79```

**Comment by dubwoc** [comment]
I have the same problem when I call this just with -g for getting the album artwork. If I add art to any of the offending items (sometimes it lists more than one) I get further, unsurprisingly but perhaps helpful. 


>docker exec ampache /var/www/bin/cli  run:updateCatalog -g
```
Reading Catalog: "Bobs"
Start searching new media art
Error Call to undefined method stdClass::getId()
(thrown in /var/www/src/Module/Art/Collector/SpotifyCollectorModule.php:173)

Stack Trace:

  0) Ampache\Module\Art\Collector\SpotifyCollectorModule->collect()
     at /var/www/src/Module/Art/Collector/ArtCollector.php:146
  1) Ampache\Module\Art\Collector\ArtCollector->collect()
     at /var/www/src/Repository/Model/Catalog.php:1896
  2) Ampache\Repository\Model\Catalog::gather_art_item()
     at /var/www/src/Repository/Model/Catalog.php:2002
  3) Ampache\Repository\Model\Catalog->gather_art()
     at /var/www/src/Module/Catalog/Update/UpdateCatalog.php:192
  4) Ampache\Module\Catalog\Update\UpdateCatalog->update()
     at /var/www/src/Module/Cli/UpdateCatalogCommand.php:70
  5) Ampache\Module\Cli\UpdateCatalogCommand->execute()
     at /var/www/vendor/adhocore/cli/src/Application.php:366
  6) Ahc\Cli\Application->doAction()
     at /var/www/vendor/adhocore/cli/src/Application.php:280
  7) Ahc\Cli\Application->handle()
     at /var/www/bin/cli:79
You All Look the Same to Me - CD2
```

**Comment by lachlan-00** [comment]
you're right, wtf is with all these mistakes from me this week :(

**Comment by mediadev123** [comment]
> you're right, wtf is with all these mistakes from me this week :(

Mistakes happen, if you are having a bad week, just take it easy and not worry about an open source project until you have energy again

**Comment by dubwoc** [comment]
+1 to what Mediadev123 said.  Thank you for spending so much time on this project I use it all the time and appreciate all the work you put into it!!!

**Comment by mediadev123** [comment]
This seems to be fixed as of 1930decb8bc073003567dc9b44138a4d6dd8acf3
