### ISSUE TITLE
Webplayer does not play Radiostreams 

### ISSUE THREAD

**Issue by essagl** [ampache/ampache#991]
Version 3.8.0 Radiostreams that play in external player (Stream) do not play with internal Webplayer.
see picture 
![ampache](https://cloud.githubusercontent.com/assets/7497666/10521193/b7708714-736e-11e5-8c9a-44a4857d8889.jpg)

**Comment by Afterster** [comment]
Could you look on #683? Looks the same issue for me.

**Comment by essagl** [comment]
No,it seems to be another issue. I created a radiostation with the direct URL
(http://ndr-ndrkultur-mp3.akacast.akamaistream.net/7/527/273758/v1/gnl.akacast.akamaistream.net/ndr_ndrkultur_mp3)
, but got the same "Unsupported" message.

**Comment by Afterster** [comment]
I believe it was fixed on develop branch as it is working on my side. Could you try with develop branch for testing purpose? Thanks.

**Comment by Afterster** [comment]
This issue doesn't exist on development version, closing this.

**Comment by essagl** [comment]
I updated to version 3.8.2. but the describes issue still remains:

Here is the excerpt from the logfile:
2016-02-20 21:13:03 [admin] (session) -> mii4pcshqob8e53b25joevkvi2 has been extended to Sat, 20 Feb 2016 22:13:03 +0100 extension length 3600
2016-02-20 21:13:03 [admin] (ajax.server.php) -> Called for page: {stream}
2016-02-20 21:13:03 [admin] (stream.ajax.php) -> Called for action {directplay}
2016-02-20 21:13:03 [admin] (stream.ajax.php) -> Play type {}
2016-02-20 21:13:03 [admin] (session) -> mii4pcshqob8e53b25joevkvi2 has been extended to Sat, 20 Feb 2016 22:13:03 +0100 extension length 3600
2016-02-20 21:13:03 [admin] (session) -> mii4pcshqob8e53b25joevkvi2 has been extended to Sat, 20 Feb 2016 22:13:03 +0100 extension length 3600
2016-02-20 21:13:03 [admin] (stream.php) -> Asked for {play_item}.
2016-02-20 21:13:03 [admin] (stream.php) -> Stream Type: web_player Media IDs: [{"object_type":"live_stream","object_id":"14"}]
2016-02-20 21:13:03 [admin] (session) -> Session created: 8e28696a99c057e5edabb4260f824b74
2016-02-20 21:13:03 [admin] (stream_playlist.class.php) -> Adding url {{"properties":["url","title","author","time","info_url","image_url","album","type","codec","track_num"]}}...
2016-02-20 21:13:03 [admin] (stream_playlist) -> Generating a {web_player} object...
2016-02-20 21:13:03 [admin] (webplayer.class.php) -> Types {{"real":"","player":""}}
2016-02-20 21:13:03 [admin] (webplayer.class.php) -> Return get_media_js_param {{"title":"Radio - NDR Kultur","artist":"Ampache","filetype":"","url":"http:\/\/ndr-ndrkultur-mp3.akacast.akamaistream.net\/7\/527\/273758\/v1\/gnl.akacast.akamaistream.net\/ndr_ndrkultur_mp3"}}
2016-02-20 21:13:03 [admin] (webplayer.class.php) -> Types {{"real":"","player":""}}
2016-02-20 21:13:03 [admin] (webplayer.class.php) -> Return get_media_js_param {{"title":"Radio - NDR Kultur","artist":"Ampache","filetype":"","url":"http:\/\/ndr-ndrkultur-mp3.akacast.akamaistream.net\/7\/527\/273758\/v1\/gnl.akacast.akamaistream.net\/ndr_ndrkultur_mp3"}}
2016-02-20 21:13:04 [admin] (session) -> mii4pcshqob8e53b25joevkvi2 has been extended to Sat, 20 Feb 2016 22:13:04 +0100 extension length 3600
2016-02-20 21:13:04 [admin] (webplayer.class.php) -> Types {{"real":null,"player":null}}
2016-02-20 21:13:04 [admin] (webplayer.class.php) -> Types {{"real":null,"player":null}}
2016-02-20 21:13:04 [admin] (webplayer.class.php) -> Return get_media_js_param {{"title":"Radio - NDR Kultur","artist":"Ampache","filetype":null,"url":"http:\/\/ndr-ndrkultur-mp3.akacast.akamaistream.net\/7\/527\/273758\/v1\/gnl.akacast.akamaistream.net\/ndr_ndrkultur_mp3"}}
2016-02-20 21:13:08 [admin] (session) -> mii4pcshqob8e53b25joevkvi2 has been extended to Sat, 20 Feb 2016 22:13:08 +0100 extension length 3600
2016-02-20 21:13:08 [admin] (ajax.server.php) -> Called for page: {index}
2016-02-20 21:13:09 [admin] (session) -> mii4pcshqob8e53b25joevkvi2 has been extended to Sat, 20 Feb 2016 22:13:09 +0100 extension length 3600
2016-02-20 21:13:09 [admin] (ajax.server.php) -> Called for page: {index}
2016-02-20 21:14:08 [admin] (session) -> mii4pcshqob8e53b25joevkvi2 has been extended to Sat, 20 Feb 2016 22:14:08 +0100 extension length 3600
2016-02-20 21:14:08 [admin] (ajax.server.php) -> Called for page: {index}
2016-02-20 21:14:09 [admin] (session) -> mii4pcshqob8e53b25joevkvi2 has been extended to Sat, 20 Feb 2016 22:14:09 +0100 extension length 3600
2016-02-20 21:14:09 [admin] (ajax.server.php) -> Called for page: {index}

Maybe it is a configuration problem?

**Comment by essagl** [comment]
![bildschirmfoto vom 2016-02-20 21 13 21](https://cloud.githubusercontent.com/assets/7497666/13198965/748497ca-d817-11e5-84e3-2fc5df495902.png)

**Comment by Afterster** [comment]
Mhh looks clear to me with your screenshot now :smile:.
You have to edit your radio stations and set the codec field value to MP3. It cannot be determined automatically.

**Comment by essagl** [comment]
Thanks for the solution. - It would not be an issue if input forms would mark and force data in required input fields.

**Comment by Afterster** [comment]
yep, done.
